# This is a basic workflow to help you get started with Actions

name: Wakatime Weekly Stats

on:
  schedule:
    # Run on every Sunday, 12:00 AM IST (5:30 AM UTC)
    - cron: '30 5 * * 1'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Collect weekly stats
        run: |
          curl -v "https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=${WAKATIME_API_KEY}" -o wakatime-archive/$(date --date='TZ="Asia/Kolkata" 1 week ago' "+%V-%Y").json
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Commit to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[ci]: collect wakatime stats"
          git push origin master
